addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 235fb846-efe2-464e-889b-4e04c18a8054
jdk: [oraclejdk8]
language: java
script: [mvn install, ./df-build.sh]
sudo: 'false'
# Modified by Insights Service at 2016-04-05 08:34:54.401133
